openapi: 3.0.3
info:
  title: Activities Availability Commission Update API
  version: 1.0.0
  description: 'API for activities: tickets, modalities, availability, prebook, payments, and booking. Authentication via API Key.'
servers:
- url: https://api-dev.despegar.com/v3/activities-api
  description: Sandbox
- url: https://apis-uat.despegar.com/v3/activities-api
  description: UAT
- url: https://api.despegar.com/v3/activities-api
  description: Production
security:
- ApiKeyAuth: []
tags:
- name: Commission Update
paths:
  /commissions/update:
    put:
      tags:
      - Commission Update
      summary: Commission Update
      description: This service detects price variations for a product, providing the differences between the original and the updated value.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prebook_id:
                  type: string
                commission:
                  type: number
              required:
              - prebook_id
              - commission
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  commission:
                    type: object
                    properties:
                      amount:
                        type: number
                      max_amount:
                        type: number
                      min_amount:
                        type: number
                  total:
                    type: number
                  currency:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: INVALID_FILTER
                  message:
                    type: string
                    example: Invalid parameter
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: INVALID_FILTER
                  message:
                    type: string
                    example: Invalid parameter
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-apikey
    BearerAuth:
      type: http
      scheme: bearer
x-readme: {}
